# Configuration for the Machine Learning Project

filenames:
  - Bitcoin.csv
  - XRP.csv
  - Zcash.csv
  - Stellar.csv
  - Monero.csv
  - Ethereum.csv
  - Litecoin.csv
  - OMG_Network.csv
  - Waves.csv
  - Dash.csv
  - IOTA.csv
  - EOS.csv
  - Cardano.csv
  - Decentraland.csv
  - Chainlink.csv
  - Tezos.csv
  - Maker.csv
  - Filecoin.csv
  - Theta.csv
  - BinanceCoin.csv
  - BitcoinCash.csv
  - EnjinCoin.csv
  - Tron.csv
  - EthereumClassic.csv
  - NEO.csv

wavelet: 'db4'
level: 5
periods:
  - before_pandemic
  - during_pandemic
  - after_pandemic
  - whole_set
scaling: true

analyzed_crypto: 'Bitcoin'  # This can be changed as needed

model_name: 'GRU'  # Options: ANN, GRU
feature_extraction_method: 'LSTM_AE_DWT'  # Options: PCA_DWT, LSTM_AE_DWT

test_size: 0.2
epochs: 100
batch_size: 32

h: 14  # Lookback period (~history parameter ~input sequence length)
